FROM node:16

WORKDIR /hehebot

ENV NODE_ENV=production

ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY build.uglified /hehebot/build

CMD ["node", "--experimental-json-modules", "build/index.js"]
